import "./globals.css";
import { Inter } from "next/font/google";
import Sidenav from "./components/sidenav";
import Navbar from "./components/pagenav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "linkifyapp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`  } >
        <div className="w-full flex   h-screen box-border overflow-hidden">
          <div className="w-1/6 bg-gray-800 sticky">
            <Sidenav menuItems={[]} />
          </div>

          <main className="w-5/6 flex flex-col overflow-y-scroll ">
            <Navbar />
            <div className="p-4 box-border"> {children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
